### ISSUE TITLE
[Feature request] Directly paste selected item from history

### ISSUE THREAD

**Issue by erikw** [rickyrockrat/parcellite#1]
In macOS I've started to use [ClipMenu](http://www.clipmenu.com/) and it has a  very nice option to enable so that directly when you pick an item from the clipboard history, it is inserted at the cursor. For me this is exactly what I want to do 97.5% of the times, so it saved my quire a few keystrokes over time.

I would love to see this in Parcellite too.

(It seems like this is not the place where feature requests are done, since this is the first issue. Where is the right place to post this) 

Thanks

**Comment by rickyrockrat** [comment]
It should already be there. That's what the auto-paste option does. It requires xdotool to be installed.
