### ISSUE TITLE
difficult compilation due to hardwired paths in Makefiles

### ISSUE THREAD

**Issue by bdantas** [rickyrockrat/parcellite#103]
I love parcellite and package it for Tiny Core Linux (x86 and x86_64 repos).

Compiling parcellite on TCL recently became difficult due to all the hardwired paths in the Makefiles. The issue is that in some distros (such as TCL), executables do not all live in /usr/bin. In the specific case of TCL, most executables (viz. all those provided by packages) actually live in /usr/local/bin because /usr/bin is reserved for executables that are part of the base system.

Eventually I was able to compile parcellite after the following preparatory steps:

```
sudo ln -s /usr/local/bin/msgfmt /usr/bin/msgfmt
cd parcellite-1.2.5
sed -i 's|/usr/bin/|/usr/local/bin/|' ./data/Makefile
sed -i 's|/usr/local/bin/install|/usr/bin/install|' ./data/Makefile
```

Would it be possible to not have all those hardwired paths in the Makefiles? If not, no big deal because compilation is successful after the above workaround. I just wanted to bring this difficulty to your attention.

**Comment by rickyrockrat** [comment]
Yes, I see what you mean. So here's a proposed solution: suppose this is used instead:

INSTALL?=$$(PATH=/usr/bin:/usr/local/bin:/usr/sbin:/bin:/sbin:$HOME/.local/bin which install)

for each hard coded executable?

**Comment by rickyrockrat** [comment]
I created a branch called 'unhardcode' If you want to check that out and let me know if it works for you, I can close this.

**Comment by bdantas** [comment]
Thanks, rickyrockrat! I checked out the 'unhardcode' branch. It seems `data/Makefile` still has some hardcoded paths which are causing trouble. When I change the "po dir" section of data/Makefile to this:

```# po dir
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
GMSGFMT = $(shell which msgfmt)
MSGFMT = $(GMSFMT)
XGETTEXT = $(shell which xgettext)
INTLTOOL_UPDATE = $(shell which intltool-update)
INTLTOOL_EXTRACT = $(shell which intltool-extract)
MSGMERGE = INTLTOOL_EXTRACT="$(INTLTOOL_EXTRACT)" XGETTEXT="$(XGETTEXT)" srcdir=$(srcdir) $(INTLTOOL_UPDATE) --gettext-package $(GETTEXT_PACKAGE) --dist
GENPOT   = INTLTOOL_EXTRACT="$(INTLTOOL_EXTRACT)" XGETTEXT="$(XGETTEXT)" srcdir=$(srcdir) $(INTLTOOL_UPDATE) --gettext-package $(GETTEXT_PACKAGE) --pot
INTLTOOL_MERGE = $(shell which intltool-merge)
```
Then I'm able to compile the 'unhardcode' branch without any problems :)

Not having hardcoded paths in the Makefiles will make maintaining parcellite much more pleasant. Many thanks!

**Comment by rickyrockrat** [comment]
oops. I missed checking that file in. Please pull and try again.

**Comment by bdantas** [comment]
This pull request includes all the changes you made plus the additional file: https://github.com/rickyrockrat/parcellite/pull/104
