### ISSUE TITLE
Cli option to remove item

### ISSUE THREAD

**Issue by pklopotowski** [rickyrockrat/parcellite#12]
I want to use parcellite together with my password manger (pass). my password manager removes password from clipboard after given period of time. but I have no idea how to avoid passing a password to the history of parcellite. 
I thought that if there will be an option to remove last added item from parcellite I will run it after the pass manger command.

**Comment by pklopotowski** [comment]
I wrote an extension to pass

**Comment by rickyrockrat** [comment]
There isn't at this time. There is a fifo interface, but it doesn't delete things.
