### ISSUE TITLE
LibreOffice Calc paste loses formula

### ISSUE THREAD

**Issue by jdigory** [rickyrockrat/parcellite#14]
If I select a cell or cells in LibreOffice Calc (akin to Excel), and Ctrl-C to copy them, it prepares them for pasting, and the normal behavior is to copy the formula from the cell(s).

When pasting with Ctrl-V, I only get the copied cell text, no formula.

After closing Parcellite and doing the copy/paste again, I get the formula when pasting.

Is there any way to avoid the interaction problem here? Maybe exclude an application from Parcellite somehow?

**Comment by rickyrockrat** [comment]
Libre/open office is a odd bit. Unfortunately, parcellite just monitors the clipboard(s). It has no idea who did what as regards the content - it just monitors changes. Short answer - none that I know of.

**Comment by rickyrockrat** [comment]
And just for the record, I find Libre Office pretty frustrating to use as well. It's like it has it's own clipboard. MuPdf has similar issues.
