### ISSUE TITLE
Automatically restoring clipboard on application exit

### ISSUE THREAD

**Issue by stefan-reich** [rickyrockrat/parcellite#15]
Hi, I thought this was a default feature of Parcellite?

I'm using Peppermint Linux 7 with Parcellite from apt. If I copy something in, say, jEdit, then exit jEdit, and try to paste in another application, the clipboard is empty.

I can see the copied text in the Parcellite list, so it was saved. It's just not automatically put back into the clipboard again.

I'm looking for a general solution to this general Linux problem (the emptied clipboard on application exit). Preferrably one I can ship with my Java programs, but an other way will also do.

Can I configure Parcellite to do this?

**Comment by rickyrockrat** [comment]
Is Restore Empty checked? If it is, and it still happens, Please attach your parcellite.rc file, and I'll see if I can duplicate it. Some applications do not play well with Linux.

**Comment by rickyrockrat** [comment]
I'm assuming this isn't an issue anymore.
