### ISSUE TITLE
Problem with parcellite and Ubuntu MATE 18.04 indicator applet

### ISSUE THREAD

**Issue by danboid** [rickyrockrat/parcellite#22]
When parcellite is installed under Ubuntu MATE 18.04, it shows 2 icons - one in the system tray and another in the indicator applet. One shows what would usually be the left click menu whilst the other shows what would usually be in the context/RMB menu.

**Comment by rickyrockrat** [comment]
There is a compatibilty mode for the indicator applet. I believe it shows legacy apps. This may be the cause. But I have to load a new Ubuntu and fix some things on the latest release.

**Comment by rickyrockrat** [comment]
Can you build from the latest and see if the option 'on_unity' fixes this? Thanks

**Comment by rickyrockrat** [comment]
Not heard back, so I'm closing for now.
