### ISSUE TITLE
how to launch parcellite panel from the command line?

### ISSUE THREAD

**Issue by ninrod** [rickyrockrat/parcellite#23]
Hi and thanks for the software @rickyrockrat. 

I wonder how can I lauch parcellite panel from the command line. See, I use parcellite from a docker container, so there is absolutelly no bar or gnome panel whatsoever available. I can only launch X apps from the command line. 

So I was wondering if you could provide a command like `parcellite -g` to launch the graphical penal from the command line. 

thanks in advance.

**Comment by rickyrockrat** [comment]
By graphical panel, you mean the Preferences or the clipboard list? How is it useful in a docker container? I am quite curious.

**Comment by ninrod** [comment]
@rickyrockrat both. We've set up a 5GB container image with all development tools inside (vscode, intellij, vim, emacs, zsh, git, svn, all the X basic dependencies, you name it) with all the configurations needed to operate inside our environment.  So basically the developer does not have to do any installing. He just downloads our installer which configures the environment and boots up the container. 

The container is configured to see an xserver (we use the cygwin xserver, it is pretty good) running in windows. Then, anytime you fire up an X application, it appears on windows. 

It is basically a supercharged linux container which is acting as a VM, but the cool effect is that the X apps are living side by side with windows apps. this allows for pretty cool and seamless workflows. 

I've even setup some neat windows shortcuts which fire up X apps from inside the container:

So now with this setup I have access to clipboard capabilities provided by the windows X Server. I already have and xclip and xsel working perfectly, and we are capable of copying, for instance, a text from the windows notepad app to a vim app running inside our zsh shell in the container and vice versa. 

So parcellite would fill the "clipboard history" niche. 

That's why I would need to fire it up through the command line, because I don't have gnome, kde, nothing. Just pure X and the command line. I would do something like this:

```sh
# it would be useful to fire up parcellite from the command line
$ docker exec my_container parcellite -g --detached
```

**Comment by rickyrockrat** [comment]
So do you have an example container I can play with? I would be interested in supporting this.

**Comment by rickyrockrat** [comment]
Have you tried launching parcellite? You won't have an icon, but you should have the keyboard shortcuts available.

**Comment by ninrod** [comment]
@rickyrockrat. Saddly I don't  have an open source sample I can share with you. I don't think I have keyboard shortcuts enabled because cygwin x-server is what captures keyboard inputs on windows. I mean, parcellite would have to be already running and at the foreground in order for the keys to be captured, I think.

**Comment by rickyrockrat** [comment]
Not sure why I didn't just tell you to launch parcellite directly with parcellite &. I think I'll close this since you likely have moved on.

**Comment by michael-ts** [comment]
@rickyrockrat  So uh... how DO you launch the preferences panel?  I can't figure that out either!

**Comment by michael-ts** [comment]
Never mind, to answer my own question in case anybody else finds this you have to RIGHT click on the icon in the systray... for some reason I didn't see preferences the first time I tried that.

**Comment by rickyrockrat** [comment]
LOL. It's probably because Ubuntu decided there was only one click. No rights or lefts, and now everybody is confused.:)
