### ISSUE TITLE
how to use ctrl+space as a hotkey

### ISSUE THREAD

**Issue by jtmkrueger** [rickyrockrat/parcellite#34]
This is a great tool, thanks for all the work!

I'm just trying to figure out how to use ctrl + space as a hotkey combination. I get how to specify ctrl as `<Ctrl>` but I can't seem to figure out how to specify space.

**Comment by rickyrockrat** [comment]
Well, it might be a bug, since I can't get it to work either.

**Comment by jtmkrueger** [comment]
If it helps, I'm on MATE 19.10

**Comment by rickyrockrat** [comment]
OK, the key word is space.
<Ctrl>space
