### ISSUE TITLE
Attempt to unlock mutex that was not locked

### ISSUE THREAD

**Issue by Massimo-B** [rickyrockrat/parcellite#37]
Parcellite is my favourite clipboard manager since many years.
However recently it often crashes and fails to start like this:
```
$ parcellite 
Flag 0x0001, status 0, EXIT 1 STAT 0
DRM_I915No magic! Assume no history.
Attempt to unlock mutex that was not locked
Aborted
```
The history seems to be deleted or corrupted:
```
$ ls -al ~/.local/share/parcellite/
total 4
drwxr-xr-x 1 mb mb   68 26. Sep 08:31 .
drwx------ 1 mb mb 1842 26. Sep 07:51 ..
-rw-r--r-- 1 mb mb    4 28. Aug 08:05 actions
prw-r----- 1 mb mb    0 26. Sep 08:31 fifo_c
prw-r----- 1 mb mb    0 26. Sep 08:31 fifo_cmd
prw-r----- 1 mb mb    0 26. Sep 08:31 fifo_p
-rw-r--r-- 1 mb mb    0 25. Sep 15:32 history
```
Always the only solution to fix this is restoring the directory from a backup.
But even if the history is lost, why doesn't the application start anymore?

The reason why this might has appeared this time, the machine was crashed somehow, IO was blocked. I needed to reset by SYSREQ and emergency sync.

**Comment by rickyrockrat** [comment]
I suspect you have more problems than this. The mutex in question is using g_mutex_XX functions. I suggest running parcellite with strace:
strace -o /tmp/parcellite.log -f $(which parcellite) 
Then post parcellite.log. Unfortunately, I've never run into this but then your situation will be hard to duplicate. I'm assuming the mutex is stored somewhere on your disk and it thinks it is locked.

**Comment by Massimo-B** [comment]
Next time I run into this issue I'm going to provide the strace log.
Maybe it is of interest that the underlying filesystem is btrfs.

**Comment by rickyrockrat** [comment]
I'm going to assume this is due to your crashed system. If you see it again, please re-open this.

**Comment by Dieterbe** [comment]
Hi i also have this problem with version 1.2.1
Out of the blue, parcellite just refuses to start
when I start I get errors like this:
```
<stuff i copied from primary selection buffer>No magic! Assume no history.
Attempt to unlock mutex that was not locked
[1]    316828 abort (core dumped)  parcellite
```
and this:
```
<stuff i copied from primary selection buffer>No magic! Assume no history.
Attempt to unlock mutex that was not locked
[1]    316828 abort (core dumped)  parcellite
No magic! Assume no history.
Attempt to unlock mutex that was not locked
[1]    317334 abort (core dumped)  parcellite
```

**Comment by rickyrockrat** [comment]
Can you please let me know your full install? File system format? Any  steps to get it to happen? Can you verify your parcellite history file does have content at some point? Also, have you run smartctl on your drive? Is it a SSD?

It should not be core dumping. I'll see if I can duplicate a 0 len history file here.

**Comment by rickyrockrat** [comment]
Well, I duplicated your problem. Congratulations! you've discovered a bug with a zero len history file.

**Comment by rickyrockrat** [comment]
Can you pull down the master and build and make sure it resolves your problem? I can't fix the zero len file, but parcellite should start up now with the zero len file without core dumping.

**Comment by Massimo-B** [comment]
Thanks :+1:

**Comment by rickyrockrat** [comment]
So did that fix the problem? I'd like to close this if I can. Thanks.

**Comment by Dieterbe** [comment]
Hello @rickyrockrat I just tested 6410b4e124e80bc8ee511d19c0ccd8662e8f44f7 with an empty `.local/share/parcellite/history` file.
I can confirm it starts correctly, correctly recognizes the empty file, assumes no history, and seems to function normally
thank you very much for this program ! :) 

process output:
```
Unable to load pref 'disable_clear'
Unable to load pref 'save_history_Lineno'
Unable to load pref 'on_unity'
Flag 0x0001, status 0, EXIT 1 STAT 0
(parcellite:12634): Gtk-WARNING **: 11:18:44.643: Unable to locate theme engine in module_path: "clearlooks",
<some more messages about the theme>
No magic! Assume no history.
Flag 0x0001, status 0, EXIT 1 STAT 0
```

**Comment by rickyrockrat** [comment]
Thanks everyone.

**Comment by veksha** [comment]
Hello. this bug still happens on last release (1.2.1)
maybe it's time to release 1.2.2 with the fixes?

**Comment by buliasz** [comment]
It's 2023-01-18 and the bug still happens. I have Parcellite 1.2.1 (default one from Linux Mint repo). I think the message "Attempt to unlock mutex that was not locked" is quite important here and it is always with the message "No magic! Assume no history.".

**Comment by ggrrll** [comment]
same issue here  --  we still get such old v. on mint 22 

on v.:
`Parcellite 1.2.1, GTK 3.24.41` 

all fine in the latest v.
