### ISSUE TITLE
Problems with self defined commands

### ISSUE THREAD

**Issue by complexinfinity** [rickyrockrat/parcellite#38]
Hey, 

I defined this command in parcellite: 

`echo "%s" >> /home/complexinfinity/.parcellite.log`

It works, but if I try to use this command on C - code like 

`printf("\n*******COMPLETION TIME (ms) :%f\n", elapsed);`

nothing is written to .parcellite.log. 

U have an idea about this?

**Comment by rickyrockrat** [comment]
I'm not sure what you are asking, but the C command won't work. If you are using the C printf that you are compiling to a program named my_c_prog, then my_c_prog >>  /home/complexinfinity/.parcellite.log should work.
