### ISSUE TITLE
why is it loosing " and ' when pasting through xdotools?

### ISSUE THREAD

**Issue by somayn** [rickyrockrat/parcellite#39]
it is not pasting " and '  when pasting through xdotools. always losing them when pasting paths or something like that

**Comment by rickyrockrat** [comment]
Good question. Can you provide some examples? What version of parcellite? Please post your parcellite rc file.

**Comment by somayn** [comment]
sorry for not being more specific. it is linux mint 19.2/cinnamon

[rc]
RCVersion=1
use_copy=true
use_primary=false
synchronize=false
save_history=true
history_pos=true
history_x=595
history_y=1440
history_limit=10
data_size=74
item_size=123
automatic_paste=true
auto_key=false
auto_mouse=true
key_input=true
restore_empty=false
rc_edit=true
type_search=true
case_search=false
ignore_whiteonly=false
trim_wspace_begend=true
trim_newline=false
hyperlinks_only=false
confirm_clear=true
current_on_top=false
single_line=false
reverse_history=true
item_length=200
persistent_history=false
persistent_separate=false
persistent_on_top=false
persistent_delim=\\n
nonprint_disp=false
ellipsize=3
multi_user=true
icon_name=parcellite
menu_key=
history_key=F8
phistory_key=
actions_key=

**Comment by rickyrockrat** [comment]
I think this is fixed with commit 6da1c72. Please build it and see if it does.

**Comment by rickyrockrat** [comment]
I'm going to close this for now.
