### ISSUE TITLE
build from source failed early 

### ISSUE THREAD

**Issue by kgoldman** [rickyrockrat/parcellite#40]
RHEL 7.7  x86_64 3.10 kernel

autogen.sh reports

configure.ac:23: warning: macro 'AM_GLIB_GNU_GETTEXT' not found in library
configure.ac:7: error: possibly undefined macro: AC_PACKAGE_VERSION
configure.ac:23: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT

and then configure fails with

./configure: line 2825: syntax error near unexpected token `('
./configure: line 2825: ` PACKAGE=AC_PACKAGE_TARNAME()'

The lines around this are

# Define the identity of the package.

 PACKAGE=AC_PACKAGE_TARNAME()
 VERSION=AC_PACKAGE_VERSION()

**Comment by rickyrockrat** [comment]
I believe you need to install some development package for gettext at least. I'll have to check on those others.

**Comment by kgoldman** [comment]
I installed glib2-devel and gtk2-devel and got further.  However, there are still  several issues:

1 - autogen.sh says

Please create po/Makevars from the template in po/Makevars.template.
You can then remove po/Makevars.template.

How should this be done?

Please create po/Makevars from the template in po/Makevars.template.
You can then remove po/Makevars.template.

2 - It then says to run aclocal -I m4.  If this is correct, perhaps add it to the readme.

It also says "Then run autoconf".  Perhaps add this to the readme as well.

3 - It says this.  When would the user need to do this?

You might also want to copy the convenience header file gettext.h
from the /usr/share/gettext directory into your package.
It is a wrapper around <libintl.h> that implements the configure --disable-nls
option.

4 - Finally, it now fails at:

make[2]: Entering directory `/home/kgold/Downloads/parcellite/data'
make[2]: *** No rule to make target `parcellite-startup.desktop', needed by `all-am'.  Stop.

There is a parcellite-startup.desktop.in

**Comment by rickyrockrat** [comment]
This should defiantly not be this hard. I work with CentOS all the time and it always reminds me it's the Microsoft of Linux. I'll pull down a 7.7 ISO and see what I can find.

**Comment by rickyrockrat** [comment]
Nothing like a year later coming back to this. I was able to build and install on CentOS 7.x without issues.  I do see those errors, but I just ignored them and ran configure.
Here are the steps to build parcellite on a fresh install of CentOS7:
Clone the repo.
Install dependencies:
sudo yum install autoconf automake gettext gettext-common-devel intltool gtk2-devel
Run the bootstrap ( and ignore the errors):
./autogen.sh
./configure --prefix=/usr/local
make
sudo make install.

I know you've likely found a solution, but please report back if this doesn't fix the issue with building on CentOS. I need to update that script. It is really, really old.

**Comment by rickyrockrat** [comment]
See the Readme on master for the Makefile.simple solution.
