### ISSUE TITLE
How do I key bind to tilde?

### ISSUE THREAD

**Issue by gur111** [rickyrockrat/parcellite#45]
I love the program. Good work guys. 
I've already spent about 3 hours total googling it. Didn't find a way to bind the history menu to `<Ctrl>Tilde`.
Thanks for a great tool.
Alternatively if there's a command (command line) for opening the history menu I can bind it on OS lvl.

**Comment by rickyrockrat** [comment]
Hmmm. Well, the good news is that I can duplicate it here. :)

**Comment by alex-0xFF** [comment]
It's "<Ctrl>grave"

**Comment by rickyrockrat** [comment]
Yer a stinkin' genis, Alex! 
Seriously, thanks for finding that. I can confirm that works.
