### ISSUE TITLE
Not working in wayland when i press ctrl+Alt+h

### ISSUE THREAD

**Issue by ADNAN-maker** [rickyrockrat/parcellite#47]
although it works well when same keys pressed in browser. but unfortunatly not works in native gnome environment with wayland.
while as in x11 works fine

**Comment by rickyrockrat** [comment]
I'm not sure Wayland is ready for the masses...Not that you are the masses, but there are many things that do now work as expected in Wayland. I'm going to close this simply because it does work in X.

**Comment by asfernandes** [comment]
2023 now, and I'm having the same problem.
The shortcut works in Chrome, but not in the terminal when using wayland.

**Comment by savitojs** [comment]
@rickyrockrat Can we re-open this issue? As of today, Wayland has been the default display protocol for many operating systems. Hotkeys for parcellite do not work as expected in terminal and gnome native applications.

Thanks

**Comment by rickyrockrat** [comment]
We can re-open. ATM I do not have  a Wayland test box. This application is pretty heavily tied to GTK2, which supposedly is going to be gone someday.
