### ISSUE TITLE
Failed to load saved history file

### ISSUE THREAD

**Issue by johntyree** [rickyrockrat/parcellite#48]
I saved parcellite history to a file, but there appears to be no way to load it up again.

It looks like parcellite uses a binary format to persist history in `~/.local/share/parcellite/history`, but the manually saved history file is formatted like:
```
NHIST_0382 r8712u
NHIST_0383 RTL8188SU
NHIST_0384 127.0.0.1 localhost
127.0.1.1 DebianHostName
```

Is there a way to reconcile these?

**Comment by rickyrockrat** [comment]
Not really. This was provided as way to convert the binary. If you want something that feeds back into parcellite, use the one in .local.

**Comment by johntyree** [comment]
That makes the export basically useless. You should probably not expose it to end users.

**Comment by rickyrockrat** [comment]
I suppose that is your opinion. If you want text, this is your only option. The N is normal and P is persistent. If you know anything about bash, you can do whatever you want with the file.
