### ISSUE TITLE
xdotool does not stop pasting when auto paste is unchecked.

### ISSUE THREAD

**Issue by rickyrockrat** [rickyrockrat/parcellite#55]

**Comment by rickyrockrat** [comment]
If keyboard input is checked, it will paste irregardless of the auto paste setting.

**Comment by mgarridoe** [comment]
In my tests, if you have xdotool installed, parcellite will paste automatically disregarding any settings you have for Automatic paste, Keyboard or Mouse.
Also the automatic paste strips out some characters from the original text like $ or anything after ;

**Comment by rickyrockrat** [comment]
Those options are a little odd. They have to all be unchecked for xdotool to not be called. Also, the command line does some interesting things with $ and ;.

**Comment by mgarridoe** [comment]
Hi, @rickyrockrat 

Sorry for the delay.

Ok, it fixes the issue with xdotool pasting when auto paste is unchecked.

So, ; does get pasted but $ not so it remains unreliable for my everyday use.

Kind regards,

**Comment by rickyrockrat** [comment]
Since I use the tip of the master, it means whatever is on github is what I run every day. Glad to know I can close this one. 
I desperately need to get a release out, but I have a lot going on right now.
Thanks!
