### ISSUE TITLE
Small Delay when using auto paste

### ISSUE THREAD

**Issue by KonstantMan** [rickyrockrat/parcellite#57]
There is a small delay when i pick something from histroy until it's pasted where the cursor is

**Comment by rickyrockrat** [comment]
what is your cpu usage? Since it is spawing another tool, your system can have a big effect on it. This isn't a parcellite issue.

**Comment by KonstantMan** [comment]
But your application is what creates that problem i started using it instead of clipboard gnome extension ,and i like the auto paste feature but the whole system freezes when i try to paste a big text is there any way to avoid that ?

**Comment by rickyrockrat** [comment]
So send me the equivalent text size.  Is it over 131072 bytes? What is your system specs? 

If you remove the auto paste feature, does it work without freezing?

If you have a reasonable amount of text with the autopaste, does it work correctly?

I highly suspect it is a xdotool/command line issue, but I'll be glad to look at it if you give me enough details to duplicate it here.
