### ISSUE TITLE
Category management for persistent snippets

### ISSUE THREAD

**Issue by Massimo-B** [rickyrockrat/parcellite#59]
FeatureRequest:

Hello,

please add categories for persistent clipboard entries. This could make it easier to have a longer text snippet library. Please also add a shortcut to jump to the persistent entries.
For now I need to jump to END and scroll all the unsorted snippets.

Best regards.

**Comment by Massimo-B** [comment]
I didn't notice that hotkey, but it does not work. I tried all versions like
<Ctrl><Alt>Y
<Ctrl><Alt>X
<Ctrl><Alt>B

while the
<Ctrl><Alt>V
for History key combination still works.
I'm running Xfce and have not overwritten those combinations.

**Comment by rickyrockrat** [comment]
You have to check 'persistent as a separate list' for the persistent hot key to work. Too many options with parcellite.
You also have to make sure something else like X is not using it.

**Comment by Massimo-B** [comment]
I see, working now, hard to find. Maybe add some helper text to the gui about that dependence.
