### ISSUE TITLE
Review/Update of pt_BR.po

### ISSUE THREAD

**Issue by marcelocripe** [rickyrockrat/parcellite#64]
Hello Mr RickyRockRat,

Please accept my review of pt_BR.po. The main actions are: humanization of the texts automatically translated by an internet translator, adaptations and adaptations of the texts so that they can make complete sense in my language, revision of the writing of capital and small letters according to the original text in English.

I thank you for developing and maintaining the program.

marcelocripe
(Original text in Brazilian Portuguese language)

- - - - -

Olá Senhor RickyRockRat,

Por favor, aceite a minha revisão do pt_BR.po. As principais ações forma: humanização dos textos traduzidos automaticamente por tradutor da internet, adaptações e adequações dos textos para poderem fazer sentido completo em meu idioma, revisão da escrita das letras maiúsculas e minúsculas conforme o texto original em idioma Inglês.

Eu agradeço por desenvolver e manter o programa.

marcelocripe
(Texto original em idioma Português do Brasil)
[parcellite_pt_BR_13-01-2022.po.zip](https://github.com/rickyrockrat/parcellite/files/7865417/parcellite_pt_BR_13-01-2022.po.zip)

**Comment by rickyrockrat** [comment]
Added to tip.
