### ISSUE TITLE
Panel should appear above status bar

### ISSUE THREAD

**Issue by jdalbey** [rickyrockrat/parcellite#72]
This seems like a UI defect to me.  When the Parcellite icon is clicked, the bottom of the panel that appears overlaps the status bar. (I'm using Linux Mint).  In fact, it seems that the bottom right corner of the panel is located exactly where the mouse is clicked. Here's an example:
![parcellite_1](https://user-images.githubusercontent.com/7251133/155197683-79af4db9-ec7b-46d5-88b8-cfdacbfebcb2.png)
 
This positioning is different from other similar applications that align the bottom of the panel with the top of the status bar.  See this example of Dropbox:
![dropbox_panel](https://user-images.githubusercontent.com/7251133/155198191-3c7b2e68-106c-4b80-85a0-38371e9f3dcb.png)

The problem with Parcellite's positioning occurs in this use case:  Frequently I want to examine the items on the clipboard but not select any of them.  They way I would like to do this is to:
1. click on the Parcellite icon and leave the mouse resting where clicked.
2. read the items in the list.
3. click the mouse again to make the panel disappear.

Currently what happens on step 3 is that Parcellite thinks I clicked on the "clear" menu option and presents me with the Clear History dialog. 
If the panel were displayed above the status bar, then clicking the mouse in step 3 would work as desired.

**Comment by rickyrockrat** [comment]
Hmm. It is irritating. I use hotkeys, so I've never cared. There is a position history option, but it is not ideal. A good workaround until I fix it.

**Comment by rickyrockrat** [comment]
On XFCE4 4.18, the left-click is completely broken for some reason. I have to click and hold the mouse button for the menu to stay up, but I did move the menu up (and history to the top) with commit f6047a3, so closing this.
