### ISSUE TITLE
Parcellite automatically launches on start-up

### ISSUE THREAD

**Issue by rgreen5** [rickyrockrat/parcellite#73]
Linux Mint 20.1

AFAIK, Parcellite should not launch itself automatically on boot up; but, still, the icon appears every time in the panel. Is this the correct modus operandi or a bug? IMV, there should be an option to make Parcellite a start-up app. but the default should be manual launch.

**Comment by rickyrockrat** [comment]
Parcellite does not launch itself. There is either a setting in mint or you have an autostart file set up.

**Comment by rgreen5** [comment]
Apologies. It appears to have been automatically added to the list of startup apps.
