### ISSUE TITLE
Compiling with makefile.simple fails on Ubuntu 22.04

### ISSUE THREAD

**Issue by felagund** [rickyrockrat/parcellite#80]
This is a follow up to https://github.com/rickyrockrat/parcellite/issues/52

I just tried to install Parcellite on Ubuntu 22.04 and with makefile simple (I followed the readme), it fails with:

```
sudo make -f Makefile.simple install prefix=/usr/local
mkdir -p /bin
cp  /bin
cp: missing destination file operand after '/bin'
Try 'cp --help' for more information.
make: *** [Makefile.simple:36: install] Error 1
```

Compiling the traditional way works.

**Comment by rickyrockrat** [comment]
It should be fixed. Thank you.
