### ISSUE TITLE
Parcellite hangs up

### ISSUE THREAD

**Issue by paolobenve** [rickyrockrat/parcellite#81]
Parcellite 1.2.1, GTK 2.24.33, on ubuntu 22.04

Reproduce:
- ctl-alt-x to open permanent list
- edit an item
- ctl-alt-h to open non-permanent list -> parcellite hangs up, and you must kill it and rerun.

**Comment by rickyrockrat** [comment]
Duplicate of #69 
https://github.com/rickyrockrat/parcellite/issues/69
