### ISSUE TITLE
Where do text snippets get stored?

### ISSUE THREAD

**Issue by Marek-Moehling** [rickyrockrat/parcellite#82]
I'd like to backup my texts regularly, does anyone know the path? Couldn't find anything in `~/.config/parcellite` or in `~/.local/share/parcellite`.

**Comment by Marek-Moehling** [comment]
I found it after checking with an hex editor, it's:
`/.local/share/parcellite/history`

**Comment by rickyrockrat** [comment]
You can also export your history to a file.
