### ISSUE TITLE
Can't manually edit or remove single entries

### ISSUE THREAD

**Issue by Massimo-B** [rickyrockrat/parcellite#85]
Because of https://github.com/keepassxreboot/keepassxc/issues/9842 it might by important to edit or remove single entries, which actually should already be supported but doesn't work:

parcellite-1.2.1
I have set
[x] Use Copy (Ctrl-C)
[x] Use Primary (Selection)
[ ] Synchronize clipboards

Using Ctrl+Alt+V I get my Parcellite menu, I walk to the entry I like to edit or remove, I press Alt+E, the edit field doesn't show the selected entry but only my current primary clipboard.

**Workaround**
I need to select the target entry first to make it primary, then I need to open the menu again, and edit that first primary entry.

Please fix that and also provide a shortcut for quick deletion of single entries.

**Comment by rickyrockrat** [comment]
It already exists. Pop up the history, hold the Ctrl key then right-click. The item will be struck through. When the menu closes, the item is deleted. You can do multiple items by holding the shift, the right-dragging down the list. This is documented in the man page, and please upgrade to 1.2.3.
