### ISSUE TITLE
Supporting Clear-Clipboard request API

### ISSUE THREAD

**Issue by Massimo-B** [rickyrockrat/parcellite#86]
parcellite-1.2.1

As figured out in https://github.com/keepassxreboot/keepassxc/issues/9842 parcellite does ignore empty/clear clipboard requests from a password manager.

**Comment by Sfrisio** [comment]
I face the same problem with Parcellite 1.2.1 and KeePassXC 2.7.4

**Comment by rickyrockrat** [comment]
There is a command fifo in .local/share/parcellite/ that accepts these commands:
stop_pri, stop_cli, stop_all, run_pri, run_cli, run_all, clear_all
You can play with that. if you run clear_all, it will clear your history.

echo 'clear_all' > ~/.local/share/parcellite/fifo_cmd

**Comment by Massimo-B** [comment]
Is that documented somewhere? How do the other commands work? Is that some standard API as it is used by other clipboard managers?
How is it possible for a password manager to delete the single entry of the password after a timeout?

**Comment by rickyrockrat** [comment]
It is not documented anywhere besides the code. I will add it to the man page. This is not a standard API, but rather an experimental feature request by users. At the current time, there is no way to clear just one entry from the list.  The password manager in question would need to be able to write to the fifo. Hope that helps.

**Comment by Massimo-B** [comment]
I'm sure they won't integrate a custom API of a small clipboard manager project, if there already is a standard:
https://github.com/keepassxreboot/keepassxc/issues/9842#issuecomment-1725221584
So far I have not  found what standard that is and how other clipboard managers are doing that.

**Comment by gcolpart** [comment]
From KeepassXC developer (https://github.com/keepassxreboot/keepassxc/issues/9842#issuecomment-1719170286) :

```
[…] they are clearly ignoring an "empty"/clear clipboard request.
They also seem to be ignoring the freedesktop.org standard to indicate not to store an entry in the clipboard history.

```
