### ISSUE TITLE
Make DEB or RPM packages how?

### ISSUE THREAD

**Issue by l0ddej0kk0** [rickyrockrat/parcellite#99]
Hi
in files list i see two folders deb containing files pertaining to packages of those formats.
Is there a prescribed way to do this?
In the Makefile i saw no pertinent targets.
regards, l0ddej0kk0

**Comment by rickyrockrat** [comment]
There should be a spec file in the rpm folder, and if you know how to use rpm-build, you should be able to build...but now that I look at the spec file, it's pretty old. I can update.

**Comment by rickyrockrat** [comment]
There is a prescribed way to do it - per the deb/rpm documentation. The deb packages used the ppa system at one point, but when Debian started including this was no longer necessary. For Red Hat, the rpm build process should be used. Both are a little painful.

**Comment by l0ddej0kk0** [comment]
Hi,

On Fri, 01 Nov 2024 00:54:50 +0100, rickyrockrat
***@***.***> wrote:
> There is a prescribed way to do it - per the deb/rpm documentation. The
> deb packages used the ppa system at one point, but when Debian started
> including this was no longer necessary. For Red Hat, the rpm build
> process should be used. Both are a little painful.

My question was aimed at a clean package installation of your current
version 1.2.5 IIRC, to see if the bug still persists in the current
version.
Right now, the Ubuntu 24.04 sports a v1.2.1-8build2 with my reported bug.

Looks like i'll just compile it, following
https://github.com/rickyrockrat/parcellite/blob/master/README.

Though i didn't get clearly what happens on make install:
What is MAKE's value and how does it get there?
Which files (besides the binary) do get installed and where?
--
best regards,
-- Wolf Lichtenberger
